/**
 * Target areas for the ATS test. An ATS ranks a CV by how many of the role's keywords it finds, so without a job ad
 * the test compares the CV with the words that show up most in Argentine job ads of that area.
 * Each keyword lists its accepted spellings separated by "|" (without accents, lower case): any of them counts.
 */
export type RoleArea = { id: string; label: string; keywords: string[] }

export const ROLE_AREAS: RoleArea[] = [
  { id: 'administracion', label: 'Administración y contabilidad', keywords: ['excel', 'facturacion', 'proveedores|cuentas a pagar', 'cobranza|cuentas a cobrar', 'conciliacion', 'liquidacion', 'tango|sap|bejerman|erp', 'afip|arca|impuestos|iva', 'administrativo|administrativa|administracion', 'contabilidad|contable|asientos', 'tesoreria', 'presupuesto', 'documentacion|archivo', 'informes|reportes', 'pagos', 'balance'] },
  { id: 'atencion', label: 'Atención al cliente y call center', keywords: ['atencion al cliente', 'reclamos', 'consultas', 'call center|contact center', 'crm|salesforce|zendesk', 'atencion telefonica|telefonica|telefonico', 'chat|whatsapp|mail', 'resolucion', 'satisfaccion', 'postventa', 'ventas', 'turnos|agenda', 'facturacion', 'caja', 'objetivos|metas', 'excel|office'] },
  { id: 'comercio', label: 'Comercio, ventas y supermercados', keywords: ['ventas|vendedor', 'atencion al cliente', 'caja|cajera|cajero', 'reposicion|repositor', 'stock|inventario', 'objetivos|metas', 'cobro|cobranza|medios de pago', 'exhibicion|gondola|visual', 'facturacion', 'arqueo|cierre de caja', 'promociones', 'postventa', 'fidelizacion', 'pedidos', 'sucursal|local|tienda', 'comision'] },
  { id: 'logistica', label: 'Logística y depósito', keywords: ['deposito', 'stock|inventario', 'picking', 'preparacion de pedidos|armado de pedidos', 'carga|descarga', 'autoelevador|clark|zorra', 'remitos', 'recepcion de mercaderia|recepcion', 'despacho|distribucion', 'expedicion', 'wms|sap', 'fifo|rotacion', 'control de calidad', 'reparto|entregas|rutas', 'licencia de conducir|registro', 'seguridad e higiene|epp'] },
  { id: 'gastronomia', label: 'Gastronomía, hotelería y turismo', keywords: ['cocina|cocinera|cocinero', 'mozo|moza|camarera|camarero|salon', 'barra|bartender|barista', 'manipulacion de alimentos|manipulador|bromatologia', 'higiene|limpieza', 'atencion al cliente', 'caja', 'mise en place|preparacion', 'comandas|pedidos', 'delivery', 'insumos|stock', 'turnos rotativos|fines de semana', 'eventos', 'reservas|check in|recepcion', 'housekeeping|mucama', 'ingles|idiomas'] },
  { id: 'salud', label: 'Salud y enfermería', keywords: ['enfermeria|enfermera|enfermero', 'pacientes', 'signos vitales', 'medicacion|farmacos|farmacologia', 'historia clinica', 'internacion|guardia|terapia', 'curaciones', 'bioseguridad', 'matricula', 'triage|emergencia', 'cuidados', 'protocolos', 'rcp|reanimacion', 'obra social|prepaga', 'turnos', 'registros|planillas'] },
  { id: 'it', label: 'Tecnología y sistemas', keywords: ['javascript|typescript', 'python|java|c#|php', 'sql|base de datos', 'react|angular|vue', 'node', 'git', 'api|rest', 'aws|azure|gcp|cloud', 'docker|kubernetes', 'testing|qa', 'scrum|agile|agil', 'linux', 'soporte|helpdesk|mesa de ayuda', 'redes', 'html|css', 'jira'] },
  { id: 'rrhh', label: 'Recursos humanos', keywords: ['seleccion|reclutamiento', 'entrevistas', 'liquidacion de sueldos|nomina|payroll', 'capacitacion', 'onboarding|induccion', 'legajos', 'clima laboral', 'convenio|lct|ley de contrato', 'busquedas|perfiles', 'linkedin', 'evaluacion de desempeno|desempeno', 'beneficios', 'ausentismo|licencias', 'f931|afip|arca', 'comunicacion interna', 'excel'] },
  { id: 'marketing', label: 'Marketing y comunicación', keywords: ['redes sociales|social media', 'contenido', 'instagram|facebook|tiktok', 'campanas|campaña', 'meta ads|google ads|publicidad|pauta', 'seo|sem', 'analytics|metricas|kpi', 'branding|marca', 'canva|photoshop|illustrator|adobe', 'email marketing|mailing', 'comunicacion', 'community manager', 'estrategia', 'eventos', 'redaccion|copywriting', 'presupuesto'] },
  { id: 'educacion', label: 'Educación', keywords: ['docente|profesor|profesora|maestra|maestro', 'alumnos|estudiantes', 'planificacion', 'clases', 'evaluacion', 'nivel inicial|primario|secundario', 'titulo docente|profesorado', 'aula|aulico', 'proyectos', 'classroom|moodle|plataformas|tecnologia educativa', 'inclusion', 'familias', 'actos|actividades', 'apoyo escolar|tutoria', 'capacitacion', 'didactica|didactico'] },
  { id: 'industria', label: 'Producción, industria y mantenimiento', keywords: ['produccion', 'operario|operador', 'maquinas|maquinaria', 'mantenimiento', 'seguridad e higiene|epp', 'control de calidad|calidad', 'turnos rotativos', 'linea de produccion|linea', 'mecanica|electricidad|electrica|electromecanica', 'herramientas', 'iso|bpm|5s', 'planta|fabrica', 'soldadura|torno', 'planos', 'autoelevador', 'tecnico|secundario completo'] },
]

export const OTHER_AREA = 'otra'
