-- Order numbers start at #1 with the first real order. Test orders from the admin account
-- move to the 90000 range and are cancelled, so they leave the numbering and the active list.
alter table public.orders alter column number set generated by default;

update public.orders o set number = o.number + 90000, status = 'cancelled',
  admin_note = trim(coalesce(o.admin_note, '') || ' Pedido de prueba.'), updated_at = now()
from public.profiles p where p.id = o.user_id and p.role = 'admin' and o.number < 90000;

update public.orders set number = 1, updated_at = now()
where number = (select min(number) from public.orders where number < 90000);

alter table public.orders alter column number restart with 2;
