create table public.faqs (
  id uuid primary key default gen_random_uuid(),
  section text not null default 'general' check (section in ('cv','asesorias','general')),
  question text not null,
  answer text not null,           -- may contain {{precio:<product_id>}} and {{extra:<group_id>}}
  keywords text[] not null default '{}',
  show_on_page boolean not null default false,   -- also listed in the page's FAQ section
  active boolean not null default true,
  sort integer not null default 0,
  created_at timestamptz not null default now()
);
alter table public.faqs enable row level security;
create policy "faqs read" on public.faqs for select to anon, authenticated using (active or (select public.is_admin()));
create policy "faqs admin write" on public.faqs for all to authenticated using ((select public.is_admin())) with check ((select public.is_admin()));

insert into public.faqs (section, question, answer, keywords, show_on_page, sort) values
('cv','¿Qué es un CV optimizado para filtros ATS?','Muchas empresas usan sistemas (ATS) que leen los CV automáticamente antes de que los vea una persona. El CV ATS está armado con la estructura y las palabras clave que esos sistemas reconocen, para que tu postulación no quede descartada por el formato.', array['ats','filtro','filtros','sistema','robot','descartan'], true, 1),
('cv','¿Qué incluye cada pack de CV?','Pack Simple ({{precio:cv-simple}}): revisión de tu CV anterior y 2 CV nuevos, uno moderno y uno optimizado para ATS. Pack Medium ({{precio:cv-medium}}): los 2 CV más carta de presentación. Pack Premium ({{precio:cv-premium}}): los 2 CV, carta de presentación y perfil de LinkedIn completo.', array['pack','packs','incluye','simple','medium','premium','precio','precios','cuesta','sale','valor','diferencia'], false, 2),
('cv','¿Cuánto tarda mi CV?','3 a 4 días hábiles desde que tengo toda tu información y el pago confirmado. No trabajo fines de semana, y si contratás después de las 17 hs empiezo al día siguiente por la tarde. Con la versión Express lo tenés dentro de las 24 hs hábiles por {{extra:express}} extra (avisalo antes de empezar).', array['tarda','demora','cuanto','tiempo','dias','entrega','plazo','rapido','urgente','express','24'], true, 3),
('cv','¿Hacen el CV en otros idiomas?','Sí: inglés, italiano, portugués, francés, español, alemán y otros a consultar. Cada idioma suma {{extra:idiomas}} a tu pack.', array['idioma','idiomas','ingles','italiano','portugues','frances','aleman','traduccion','traducir'], true, 4),
('cv','¿En qué plataformas cargan mi perfil?','Zonajobs, Bumeran, Computrabajo, HiringRoom, Indeed y otras a consultar: {{extra:plataformas}} cada una, sumadas a cualquier pack.', array['plataforma','plataformas','zonajobs','bumeran','computrabajo','hiringroom','indeed','cargar','carga','perfil'], true, 5),
('cv','¿Hacen el perfil de LinkedIn?','Sí. El perfil de LinkedIn solo, sin pack de CV, cuesta {{precio:linkedin}}. Si también necesitás CV, el Pack Premium ({{precio:cv-premium}}) ya lo incluye.', array['linkedin','linked','perfil'], false, 6),
('cv','¿Puedo pedir cambios?','Sí. Te paso un boceto para ajustarlo juntos y, una vez entregado, tenés 24 hs para pedir cambios sin costo. Pasado ese plazo, cada cambio cuesta $5.000.', array['cambio','cambios','modificar','modificacion','corregir','error','boceto'], true, 7),
('cv','¿Puedo mezclar rubros en un pack?','Es 1 pack por persona y por rubro: mezclar muchos rubros hace que el CV no funcione bien con los filtros ATS. Si apuntás a dos rubros distintos, lo ideal son dos packs.', array['rubro','rubros','mezclar','dos','area','areas','puesto'], true, 8),
('cv','¿En qué formato recibo mi CV?','Te entrego el formato editable (un link) y los PDF. Desde el link podés descargar el PDF cuando quieras, por ejemplo si más adelante cambiás la foto o el color. Trabajo con plantillas propias, 100% hechas por Valeria.', array['formato','pdf','word','editable','link','plantilla','plantillas','recibo'], false, 9),
('general','¿Cómo pago?','Por transferencia bancaria. Cuando confirmás tu pedido en la web te mostramos los datos para transferir y subís el comprobante ahí mismo. El trabajo empieza una vez abonado el total.', array['pago','pagar','pagos','transferencia','transferir','alias','cbu','tarjeta','mercadopago','mercado','efectivo','cuotas'], true, 10),
('general','¿Tengo que crear una cuenta para comprar?','Sí, es rápido: con tu email y una contraseña. En tu cuenta ves el estado del pedido, subís el comprobante, descargás tus e-books y ves tus cursos y sesiones.', array['cuenta','registrarme','registro','usuario','contraseña','ingresar','login','crear'], false, 11),
('general','¿Puedo cancelar mi pedido?','Una vez hecho el pedido no se puede cancelar. Si tenés dudas antes de comprar, escribinos por WhatsApp y lo vemos juntas.', array['cancelar','cancelacion','devolucion','devolver','reembolso','reintegro','arrepentimiento'], false, 12),
('general','¿Cómo me comunico con Valeria?','Por WhatsApp al 11 5106-0953, por Instagram @armadodecv.ok o por email a ayuda.armadodecv@gmail.com.', array['contacto','whatsapp','telefono','instagram','mail','email','hablar','comunicar','escribir'], false, 13),
('asesorias','¿Qué e-books hay y cuánto cuestan?','Hay tres e-books: entrevistas laborales, entrevistas virtuales y tests laborales y psicotécnicos. Cada uno cuesta {{precio:ebook}}. El Pack Plus trae 2 e-books por {{precio:asesoria-plus}}, y el Pack Premium suma una sesión 1 a 1 por Meet por {{precio:asesoria-premium}}.', array['ebook','ebooks','libro','guia','guias','entrevista','psicotecnico','psicotecnicos','plus','pack','precio','cuesta'], false, 20),
('asesorias','¿Cómo recibo los e-books?','Son archivos que podés leer desde el celular, la tablet o la computadora. Los descargás desde "Mi cuenta" apenas se confirma tu pago.', array['recibo','descargar','descarga','ebook','ebooks','archivo','llega','envian'], true, 21),
('asesorias','¿Cómo es la sesión 1 a 1?','Es una videollamada por Google Meet de 60 a 90 minutos: simulacro de entrevista o psicotécnico, feedback personalizado y trabajo sobre la ansiedad. Una vez confirmado el pago coordinamos día y horario por WhatsApp. Si faltás sin avisar con 24 hs, la sesión cuenta como hecha y hay que volver a abonarla.', array['sesion','meet','videollamada','llamada','turno','1a1','individual','simulacro','horario'], true, 22),
('asesorias','¿El test vocacional es un diagnóstico?','No. Es una herramienta de orientación (CHASIDE y TV-A): no constituye diagnóstico ni evaluación psicométrica estandarizada. Cuesta {{precio:test-vocacional}} con devolución por email, y podés sumar una devolución 1 a 1 por Meet por {{extra:devolucion}}.', array['test','vocacional','orientacion','carrera','estudiar','chaside','diagnostico'], true, 23),
('asesorias','¿Me garantiza pasar la entrevista o el psicotécnico?','Prepararte no garantiza un resultado, pero sí te permite mostrarte mejor: con menos ansiedad, más claridad y coherencia al responder. Nada de falsear respuestas.', array['garantia','garantiza','aprobar','pasar','seguro','resultado','conseguir','trabajo'], true, 24),
('general','¿Cómo veo un curso pre-grabado?','Los cursos se ven desde "Mi cuenta", con el mismo email con el que compraste, y quedan disponibles por 12 meses desde que se aprueba el pago.', array['curso','cursos','clase','clases','video','videos','grabado','ver'], false, 25);
